
  
version: '3'

services: 
  nginx:
      build: ./nginx
      ports:
      - '8080:80'
      depends_on:
      - app
      networks: 
        - node-network    

  app:
    build:
      context: ./
      dockerfile: devops/Dockerfile
    container_name: app    
    networks: 
      - node-network    
    tty: true    
    depends_on: 
       - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true    
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - node-network

networks: 
  node-network:
    driver: bridge    